project_id = "cbhyrchkkhnbcuaticnb"

[functions.send-quote-request]
verify_jwt = false

[functions.send-build-request]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.send-reset-password]
verify_jwt = false

[functions.receptionist-chat]
verify_jwt = false
